Rename project/package from bpkg-rep to bpkg-util

diff --git a/bpkg-util/package-archive.bash.in b/bpkg-util/package-archive.bash.in
--- a/bpkg-util/package-archive.bash.in
+++ b/bpkg-util/package-archive.bash.in
@@ -1,21 +1,21 @@
-# file      : bpkg-rep/package-archive.bash.in
+# file      : bpkg-util/package-archive.bash.in
 # license   : MIT; see accompanying LICENSE file
 
 # Utility functions useful for managing package archives.
 
-if [ "$bpkg_rep_package_archive" ]; then
+if [ "$bpkg_util_package_archive" ]; then
   return 0
 else
-  bpkg_rep_package_archive=true
+  bpkg_util_package_archive=true
 fi
 
 @import libbutl/manifest-parser@
 
-# We expect the user to set the bpkg_rep_bpkg variable to the bpkg program
+# We expect the user to set the bpkg_util_bpkg variable to the bpkg program
 # path.
 #
-if [ ! -v bpkg_rep_bpkg ]; then
-  echo "error: variable bpkg_rep_bpkg is not set" >&2
+if [ ! -v bpkg_util_bpkg ]; then
+  echo "error: variable bpkg_util_bpkg is not set" >&2
   exit 1
 fi
 
@@ -26,7 +26,7 @@ fi
 # Note that, in particular, it verifies that the archive file name matches the
 # package name and version.
 #
-function bpkg_rep_pkg_verify_archive () # <path>
+function bpkg_util_pkg_verify_archive () # <path>
 {
   # We can't use the process substitution for input redirect here, since such
   # a process failure is not trapped. Thus, read the manifest file into a
@@ -38,7 +38,7 @@ function bpkg_rep_pkg_verify_archive () # <path>
   # with non-zero status if that's the case. Feels a bit hackish though.
   #
   local m
-  m="$("$bpkg_rep_bpkg" pkg-verify --manifest "$1")"
+  m="$("$bpkg_util_bpkg" pkg-verify --manifest "$1")"
 
   butl_manifest_parser_start <<<"$m"
 
@@ -66,21 +66,21 @@ function bpkg_rep_pkg_verify_archive () # <path>
 # the version contains the trailing '*', then print archives for all revisions
 # of the specified version and for the exact version otherwise. For example:
 #
-# bpkg_rep_pkg_find_archives foo '*'    dir/
-# bpkg_rep_pkg_find_archives foo '1.0*' dir/
-# bpkg_rep_pkg_find_archives foo '1.0'  dir/
+# bpkg_util_pkg_find_archives foo '*'    dir/
+# bpkg_util_pkg_find_archives foo '1.0*' dir/
+# bpkg_util_pkg_find_archives foo '1.0'  dir/
 #
 # Note that the resulting archive paths include the specified directory as a
 # prefix.
 #
 # NOTE: this function can be called with overriden IFS.
 #
-function bpkg_rep_pkg_find_archives () # <name> <version> <dir>
+function bpkg_util_pkg_find_archives () # <name> <version> <dir>
 {
-  IFS=$' \t\n' bpkg_rep_pkg_find_archives_impl "$@"
+  IFS=$' \t\n' bpkg_util_pkg_find_archives_impl "$@"
 }
 
-function bpkg_rep_pkg_find_archives_impl ()
+function bpkg_util_pkg_find_archives_impl ()
 {
   local nam="$1"
   local ver="$2"
@@ -106,7 +106,7 @@ function bpkg_rep_pkg_find_archives_impl ()
     local f
     while read f; do
       local p
-      p=($(bpkg_rep_pkg_verify_archive "$f"))
+      p=($(bpkg_util_pkg_verify_archive "$f"))
 
       local n="${p[0]}"
       local v="${p[1]}"
@@ -140,12 +140,12 @@ function bpkg_rep_pkg_find_archives_impl ()
 #
 # NOTE: this function can be called with overriden IFS.
 #
-function bpkg_rep_pkg_find_archive () # <pattern> <dir>
+function bpkg_util_pkg_find_archive () # <pattern> <dir>
 {
-  IFS=$' \t\n' bpkg_rep_pkg_find_archive_impl "$@"
+  IFS=$' \t\n' bpkg_util_pkg_find_archive_impl "$@"
 }
 
-function bpkg_rep_pkg_find_archive_impl ()
+function bpkg_util_pkg_find_archive_impl ()
 {
   local pat="$1"
   local dir="$2"
@@ -161,7 +161,7 @@ function bpkg_rep_pkg_find_archive_impl ()
     if [ -n "$f" ]; then
 
       local p
-      p=($(bpkg_rep_pkg_verify_archive "$f"))
+      p=($(bpkg_util_pkg_verify_archive "$f"))
 
       printf "${p[0]}\n${p[1]}\n${p[2]}\n$f"
       return
